<?php
$messages = array();

$messages['en'] = array(
	'helpmebot' => 'Helpmebot',

	'specialpages-group-helpmebot' => "Helpmebot data",

	'accesslist' => 'Access List',
	'botmessages' => 'Messages',
	'brain' => "Brain",
	'commandlist' => 'Command List',

	'hmb-accesslist-headertext' => 'Access list is shown below.',

	'hmb-commandlist-headertext' => 'Command list is shown below.',

	'hmb-brain-headertext' => 'This is a list of all the words I recognise:',
	'hmb-action-yes' => 'Yes',
	'hmb-action-no' => 'No',

	'right-helpmebot-editmessages' => 'Edit the bot\'s message table',
    'right-helpmebot-editautogen' => 'Edit the autogenerated pages',
);
